## Importing necessary libraries required

In [10]:
import pandas as pd

In [11]:
import numpy as np

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
from sklearn.svm import SVC

In [17]:
from sklearn import metrics

In [18]:
from sklearn import cross_validation

## Loading the Dataset

In [19]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
iris_dataset = pd.read_csv(url, names=names)
iris_dataset=pd.DataFrame(iris_dataset)

## Exploring the Dataset

In [21]:
iris_dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [22]:
iris_dataset.describe()

sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Splitting the Dataset into Training and Test Set

In [23]:
X=iris_dataset.iloc[:,[0,1,2,3]]

In [24]:
X.head()

sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [25]:
y=iris_dataset.iloc[:,[4]]

In [26]:
y.head()

class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

### Splitting the Dataset into 80:20 ratio

In [27]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.2)

### Applying Logistic Regression Classifier

In [28]:
clf=LogisticRegression()

In [29]:
clf.fit(X_train,y_train)

C:\Users\ajayjaswani96\Anaconda2\envs\gl-env\lib\site-packages\sklearn\utils\validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [30]:
print clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [31]:
predicted=clf.predict(X_test)

In [38]:
print(metrics.classification_report(y_test,predicted))
print (metrics.confusion_matrix(y_test, predicted))
print 'Accuracy=%f '%(metrics.accuracy_score(y_test, predicted))

             precision    recall  f1-score   support

Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        11
Iris-virginica       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        30

[[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
Accuracy=1.000000 


### Applying Naive Bayes Classifier

In [39]:
clf = GaussianNB()

In [40]:
clf.fit(X_train,y_train)

C:\Users\ajayjaswani96\Anaconda2\envs\gl-env\lib\site-packages\sklearn\utils\validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [41]:
predicted=clf.predict(X_test)

In [42]:
print(metrics.classification_report(y_test,predicted))
print (metrics.confusion_matrix(y_test, predicted))
print 'Accuracy=%f '%(metrics.accuracy_score(y_test, predicted))

             precision    recall  f1-score   support

Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        11
Iris-virginica       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        30

[[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
Accuracy=1.000000 


### Applying K-Nearest Neighbor Classifier

In [43]:
clf=KNeighborsClassifier()

In [44]:
clf.fit(X_train,y_train)

C:\Users\ajayjaswani96\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [45]:
predicted=clf.predict(X_test)

In [47]:
print(metrics.classification_report(y_test,predicted))
print (metrics.confusion_matrix(y_test, predicted))
print 'Accuracy=%f '%(metrics.accuracy_score(y_test, predicted))

             precision    recall  f1-score   support

Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.91      0.95        11
Iris-virginica       0.91      1.00      0.95        10

avg / total       0.97      0.97      0.97        30

[[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
Accuracy=0.966667 


### Applying SVM classifier

In [48]:
clf=SVC()

In [49]:
clf.fit(X_train,y_train)

C:\Users\ajayjaswani96\Anaconda2\envs\gl-env\lib\site-packages\sklearn\svm\base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
predicted=clf.predict(X_test)

In [51]:
print(metrics.classification_report(y_test,predicted))
print (metrics.confusion_matrix(y_test, predicted))
print 'Accuracy=%f '%(metrics.accuracy_score(y_test, predicted))

             precision    recall  f1-score   support

Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        11
Iris-virginica       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        30

[[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
Accuracy=1.000000 


### Classification and Regression Trees

In [52]:
clf=DecisionTreeClassifier()

In [53]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [54]:
predicted=clf.predict(X_test)

In [55]:
print(metrics.classification_report(y_test,predicted))
print (metrics.confusion_matrix(y_test, predicted))
print 'Accuracy=%f '%(metrics.accuracy_score(y_test, predicted))

             precision    recall  f1-score   support

Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        11
Iris-virginica       1.00      1.00      1.00        10

avg / total       1.00      1.00      1.00        30

[[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
Accuracy=1.000000 
